#TRABAJO PRACTICO

## DESCRIPCION DE LA PROBLEMATICA
La empresa InnovaTech esta implementando construir y mantener su plataforma de ventas. Para ellos nos solicito analizar y entender a fondo los consumidores y con ello, personalizar mensajes hacia sus clientes. Detectar nichos de mercado que ayuden a elaborar campa√±as y obtener leads de mayor calidad. Por ende, en este analisis gestionaremos, analizaremos datos claves que resuelvan la problematica planteada.


![imagen_2024-05-04_210007869.png]()

## INSTALACION
Se realiza la instalacion de librerias necesarias para abarcar el siguiente analisis.

In [ ]:
!pip install pandas==2.2.2
#Se realiza la instalacion de libreria Pandas que nos ayudara a cargar datos provenientes de CSV, para limpieza de datos y por ultimo, para generar un reporte descriptivo.

Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 13.0/13.0 MB 73.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.0.3, but you have pandas 2.2.2 which is incompatible.
Successfully installed pandas-2.2.2

In [ ]:
import pandas as pd
#Se realiza la importacion de Pandas

In [ ]:
import os
#Se realiza la importancion de os utilizado para directorios de archivos generados.

In [ ]:
print(pd.__version__)

2.2.2

## IMPORTACION DE DATOS CSV
Se cargara los datos de cada DataSet para su visualizacion. Todos los dataset seran importados desde la web

###Customers

En esta tabla se encuentra la informacion de los clientes de la empresa.

In [ ]:
df_customer = pd.read_csv("https://raw.githubusercontent.com/aldanaba97/recursos-analisis-datos/main/14_Datasets_Originales/ecommerce_customers_dataset.csv")
#se guarda el dataframe en la variable df_customer
df_customer.head()
#Visualizacion de las 5 primeras filas del dataset

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### Products
En esta tabla se encuentra la informacion de los productos que vende la empresa.

In [ ]:
df_products = pd.read_csv("https://raw.githubusercontent.com/aldanaba97/recursos-analisis-datos/main/14_Datasets_Originales/ecommerce_products_dataset.csv")
#se guarda el dataframe en la variable df_products
df_products.head()
#Visualizacion de las 5 primeras filas del dataset

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

### Orders
En esta tabla se encuentra la informacion de las ordenes de compra de la empresa.

In [ ]:
df_orders = pd.read_csv("https://raw.githubusercontent.com/aldanaba97/recursos-analisis-datos/main/14_Datasets_Originales/ecommerce_orders_dataset.csv")
#se guarda el dataframe en la variable df_orders
df_orders.head(50)
#Visualizacion de las 5 primeras filas del dataset

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00
11,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08 00:00:00
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00
14,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21 00:00:00
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04 00:00:00
16,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06 00:00:00
17,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29 00:00:00
18,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11 00:00:00
19,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23 00:00:00
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28 00:00:00
21,f848643eec1d69395095eb3840d2051e,4fa1cd166fa598be6de80fa84eaade43,delivered,2018-03-15 08:52:40,2018-03-15 09:09:31,2018-03-15 19:52:48,2018-03-19 18:08:32,2018-03-29 00:00:00
22,2807d0e504d6d4894d41672727bc139f,72ae281627a6102d9b3718528b420f8a,delivered,2018-02-03 20:37:35,2018-02-03 20:50:22,2018-02-05 22:37:28,2018-02-08 16:13:46,2018-02-21 00:00:00
23,95266dbfb7e20354baba07964dac78d5,a166da34890074091a942054b36e4265,delivered,2018-01-08 07:55:29,2018-01-08 08:07:31,2018-01-24 23:16:37,2018-01-26 17:32:38,2018-02-21 00:00:00
24,f3e7c359154d965827355f39d6b1fdac,62b423aab58096ca514ba6aa06be2f98,delivered,2018-08-09 11:44:40,2018-08-10 03:24:51,2018-08-10 12:29:00,2018-08-13 18:24:27,2018-08-17 00:00:00
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12 00:00:00
26,acce194856392f074dbf9dada14d8d82,7e20bf5ca92da68200643bda76c504c6,delivered,2018-06-04 00:00:13,2018-06-05 00:35:10,2018-06-05 13:24:00,2018-06-16 15:20:55,2018-07-18 00:00:00
27,dd78f560c270f1909639c11b925620ea,8b212b9525f9e74e85e37ed6df37693e,delivered,2018-03-12 01:50:26,2018-03-12 03:28:34,2018-03-12 21:06:37,2018-03-21 14:41:50,2018-03-28 00:00:00
28,91b2a010e1e45e6ba3d133fa997597be,cce89a605105b148387c52e286ac8335,delivered,2018-05-02 11:45:38,2018-05-03 12:55:01,2018-05-10 16:16:00,2018-05-16 20:56:24,2018-05-23 00:00:00
29,ecab90c9933c58908d3d6add7c6f5ae3,761df82feda9778854c6dafdaeb567e4,delivered,2018-02-25 13:50:30,2018-02-25 14:47:35,2018-02-26 22:28:50,2018-03-27 23:29:14,2018-04-13 00:00:00
30,f70a0aff17df5a6cdd9a7196128bd354,456dc10730fbdba34615447ea195d643,delivered,2017-08-10 11:58:33,2017-08-12 02:45:24,2017-08-17 15:35:07,2017-08-18 14:28:02,2017-08-23 00:00:00
31,1790eea0b567cf50911c057cf20f90f9,52142aa69d8d0e1247ab0cada0f76023,delivered,2018-04-16 21:15:39,2018-04-16 22:10:26,2018-04-18 13:05:09,2018-05-05 12:28:34,2018-05-15 00:00:00
32,989225ba6d0ebd5873335f7e01de2ae7,816f8653d5361cbf94e58c33f2502a5c,delivered,2017-12-12 13:56:04,2017-12-14 13:54:13,2017-12-16 00:18:57,2018-01-03 18:03:36,2018-01-08 00:00:00
33,d887b52c6516beb39e8cd44a5f8b60f7,d9ef95f98d8da3b492bb8c0447910498,delivered,2018-02-03 12:38:58,2018-02-03 12:50:30,2018-02-05 21:26:53,2018-02-22 00:07:55,2018-03-07 00:00:00
34,b276e4f8c0fb86bd82fce576f21713e0,cf8ffeddf027932e51e4eae73b384059,delivered,2018-07-29 23:34:51,2018-07-29 23:45:15,2018-07-30 14:43:00,2018-07-31 22:48:50,2018-08-06 00:00:00
35,8563039e855156e48fccee4d611a3196,5f16605299d698660e0606f7eae2d2f9,delivered,2018-02-17 15:59:46,2018-02-17 16:15:34,2018-02-20 23:03:56,2018-03-20 00:59:25,2018-03-20 00:00:00
36,60550084e6b4c0cb89a87df1f3e5ebd9,f5458ddc3545711efa883dd7ae7c4497,delivered,2018-02-21 18:15:12,2018-02-23 02:10:52,2018-02-27 18:52:09,2018-03-13 23:58:43,2018-03-29 00:00:00
37,5acce57f8d9dfd55fa48e212a641a69d,295ae9b35379e077273387ff64354b6f,delivered,2017-07-31 21:37:10,2017-08-02 02:56:02,2017-08-03 18:32:48,2017-08-08 21:24:41,2017-08-22 00:00:00
38,434d158e96bdd6972ad6e6d73ddcfd22,2a1dfb647f32f4390e7b857c67458536,delivered,2018-06-01 12:23:13,2018-06-05 03:35:15,2018-06-08 11:49:00,2018-06-18 21:32:52,2018-07-17 00:00:00
39,7206b86ea789983f7a273ea7fa0bc2a8,3391c4bc11a817e7973e498b0b023158,delivered,2018-03-26 17:12:18,2018-03-26 17:28:27,2018-03-28 17:22:53,2018-04-05 22:11:18,2018-04-12 00:00:00
40,1e7aff52cdbb2451ace09d0f848c3699,ddaff536587109b89777e0353215e150,delivered,2017-05-19 18:53:40,2017-05-19 19:05:17,2017-05-22 10:16:07,2017-05-31 13:58:46,2017-06-12 00:00:00
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21 00:00:00
42,948097deef559c742e7ce321e5e58919,8644be24d48806bc3a88fd59fb47ceb1,delivered,2017-08-04 17:10:39,2017-08-04 17:25:11,2017-08-07 17:52:01,2017-08-12 14:08:40,2017-09-01 00:00:00
43,d22e9fa5731b9e30e8b27afcdc2f8563,756fb9391752dad934e0fe3733378e57,delivered,2018-08-04 23:25:30,2018-08-04 23:35:13,2018-08-06 15:03:00,2018-08-13 23:34:42,2018-09-13 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
45,6ebaec694d7025e2ad4a05dba887c032,4f28355e5c17a4a42d3ce2439a1d4501,delivered,2017-05-18 13:55:47,2017-05-18 14:05:17,2017-05-19 12:01:38,2017-05-29 12:47:20,2017-06-09 00:00:00
46,d17dc4a904426827ca80f2ccb3a6be56,569cf68214806a39acc0f39344aea67f,delivered,2017-05-14 20:28:25,2017-05-14 20:42:45,2017-05-16 08:17:46,2017-05-25 09:14:31,2017-06-12 00:00:00
47,25f4376934e13d3508486352e11a5db0,12fd2740039676063a874b9567dfa651,delivered,2018-05-17 16:59:11,2018-05-18 01:17:39,2018-05-18 13:02:00,2018-05-21 15:22:11,2018-05-25 00:00:00
48,5820a1100976432c7968a52da59e9364,2b56e94c2f66f2d97cfa63356f69cee8,delivered,2018-07-29 11:24:17,2018-07-29 11:44:19,2018-07-30 13:47:00,2018-08-02 22:09:11,2018-08-13 00:00:00
49,2ce1ad82022c1ba30c2079502ac725aa,7f2178c5d771e17f507d3c1637339298,delivered,2017-08-09 20:19:05,2017-08-11 04:15:29,2017-08-11 17:52:32,2017-08-16 17:16:44,2017-08-31 00:00:00

### Order- Items
En esta tabla se encuentra la informacion de los items incluidos en la orden de compra.

In [ ]:
df_orders_items = pd.read_csv("https://raw.githubusercontent.com/aldanaba97/recursos-analisis-datos/main/14_Datasets_Originales/ecommerce_order_items_dataset.csv")
#se guarda el dataframe en la variable df_orders_items
df_orders_items.head()
#Visualizacion de las 5 primeras filas del dataset

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

### Order - Payments
En esta tabla se encuentra la informacion de las formas de pago que usan los clientes de la empresa.

In [ ]:
df_orders_payment = pd.read_csv("https://raw.githubusercontent.com/aldanaba97/recursos-analisis-datos/main/14_Datasets_Originales/ecommerce_order_payments_dataset.csv")
#se guarda el dataframe en la variable df_orders_payment
df_orders_payment.head()
#Visualizacion de las 5 primeras filas del dataset

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

## LIMPIEZA DE DATOS
Se conocera la informacion de cada DataFrame: su tipo, cantidad de nulos, registros duplicados, etc. Para ello crearemos una funcion "DatosDataFrame()".

In [ ]:
def DatosDataFrame(df): #Recibe como parametro un dataframe
  print("DATOS DEL DATAFRAME");
  print("---------------------------------------------");
  print("Tipo de datos : "  );  #Tipo de datos que posee las columnas
  print(df.info());
  print("-----------------------------------------");
  print("Cantidad de nulos: "); #Se obtiene los datos nulos mediante .isnull() y se los suma con la funcion .sum()
  print(df.isnull().sum());
  print("-----------------------------------------");
  print("Cantidad de duplicados: "); #Se obtiene los registros duplicados mediantes .duplicated() y luego se los suma con .sum()
  print(df.duplicated().sum());

A continuacio, se aplicara el metodo elaborado anteriormente para cada uno de los dataframe para luego realizar modificaciones.

### Customers

In [ ]:
DatosDataFrame(df_customer);  #Se aplica el metodo en la tabla customers

DATOS DEL DATAFRAME
---------------------------------------------
Tipo de datos :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None
-----------------------------------------
Cantidad de nulos:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
-----------------------------------------
Cantidad de duplicados:
0

###Products

In [ ]:
DatosDataFrame(df_products); #Se aplica funcion en la tabla productos

DATOS DEL DATAFRAME
---------------------------------------------
Tipo de datos :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None
-----------------------------------------
Cantidad de nulos:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
-----------------------------------------
Cantidad de duplicados:
0

###Orders

In [ ]:
DatosDataFrame(df_orders); #Se obtiene la informacion de la tabla orders

DATOS DEL DATAFRAME
---------------------------------------------
Tipo de datos :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None
-----------------------------------------
Cantidad de nulos:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
-----------------------------------------
Cantidad de duplicados:
0

### Order - Items

In [ ]:
DatosDataFrame(df_orders_items); #Se aplica la funcion para la tabla Items

DATOS DEL DATAFRAME
---------------------------------------------
Tipo de datos :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None
-----------------------------------------
Cantidad de nulos:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
-----------------------------------------
Cantidad de duplicados:
0

###Order payments

In [ ]:
DatosDataFrame(df_orders_payment); #Se aplica la funcion para la tabla payment

DATOS DEL DATAFRAME
---------------------------------------------
Tipo de datos :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None
-----------------------------------------
Cantidad de nulos:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
-----------------------------------------
Cantidad de duplicados:
0

##2) TRANFORMACION DE DATOS

Se elaborara diferentes funciones que transformen ciertos datos de los dataframe evitando problemas para futuras operaciones. Se tomara decisiones en cuanto a la cantidad de nulos y asi, lograr una eficacia en el analisis que se pretenda realizar.

Teniendo en cuenta que los campos de tipo Fecha los reconoce como Object se elaborara un metodo que tranforme los datos al formato ideal, en este caso seria, Datetime.

In [ ]:
def TransformarFecha(df, nombre_columna_fecha): #El metodo recibe como parametro el dataframe y la/s columnas que deseen modificar.
   df[nombre_columna_fecha] = df[nombre_columna_fecha].apply(pd.to_datetime) #Se realiza un casteo donde se le indica que la columna pasa a ser datetime
   return df

Al igual que el caso anterior, las columnas de tipo String son consideradas como Object. Se realizara una funcion que permita realizar un casteo.

In [ ]:
def TransformarString(df, nombre_columna_string):  #El metodo recibe como parametro el dataframe y la/s columnas que deseen modificar.
 for columna in nombre_columna_string:
  df[nombre_columna_string] = df[nombre_columna_string].astype("string"); #Se realiza un casteo donde se le indica que la columna pasa a ser string
  return df

En la siguiente funcion se transformara los registros en minuscula para evitar inconvenientes con analisis de filtrado, etc.

In [ ]:
 def TransformacionMinuscula(df, columna): #El metodo recibe como parametro el dataframe y la/s columnas que deseen modificar.
  df[columna] = df[columna].str.lower(); #Se realiza una modificacion donde todos los registros deben estar en minuscula para la columna ingresada.
  return df

### Customer
Observamos los tipo de datos que tiene la tabla para aplicar las funciones realizadas anteriormente.
*   customer_id: object
* customer_unique_id: object
* customer_zip_code_prefix: int64
* customer_city: object
* customer_state: object

A continuacion se modificara las columnas de tipo object a STRING:

In [ ]:
lista_string = ["customer_id", "customer_unique_id", "customer_city", "customer_state"];
#Se realiza la transformacion de tipo de dato de las columnas que estan dentro de la lista
TransformarString(df_customer, lista_string);
#Se invoca a la funcion creada

Los datos de las siguientes columnas se pasaran a minuscula. Se modificara solo las columnas customer_city y customer_state que son aquellas donde se pueden realizar analisis.

In [ ]:
df_customer = TransformacionMinuscula(df_customer, "customer_city");
#Se transforman todos los registros de customer_city a minusculas
df_customer = TransformacionMinuscula(df_customer, "customer_state");
#Se transforman todos los registros de customer_state a minusculas

Se visualiza para comprobar los cambios

In [ ]:
df_customer.info()
df_customer.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  string
 1   customer_unique_id        99441 non-null  string
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  string
 4   customer_state            99441 non-null  string
dtypes: int64(1), string(4)
memory usage: 3.8 MB

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,sp
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,sp
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,sp
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,sp
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,sp

Se observa la cantidad de nulos para realizar una accion que no afecte el resultado de analisis que se realice.

Cantidad de nulos:
* customer_id:                 0
* customer_unique_id:          0
* customer_zip_code_prefix:    0
* customer_city:               0
* customer_state:              0

No se aplicara ninguna funcion con tratamiento de nulos.

Por ultimo, se establece la columna √≠ndices de las tablas como la clave primaria en el DataFrame.

In [ ]:
#En este caso "costumer_id" seria la columna indice
df_customer.set_index("customer_id", inplace = True)

### Products

  Observamos los tipo de datos que tiene la tabla para aplicar las funciones realizadas anteriormente.        
  
 * product_id: object
 *  product_category_name: object
 *   product_name_lenght: float64
 *   product_description_lenght : float64
 *   product_photos_qty :  float64
 *   product_weight_g : float64
 *   product_length_cm : float64
 *   product_height_cm : float64
 *   product_width_cm : float64

A continuacion se modificara las columnas de tipo object a STRING:

In [ ]:
lista_string = ["product_id", "product_category_name"];
#Se realiza la transformacion de tipo de dato de las columnas que estan dentro de la lista
TransformarString(df_products, lista_string);
#Se invoca a la funcion creada

Los datos de las siguientes columnas se pasaran a minuscula. Se modificara solo la columna product_category_name que sera necesaria para el analisis.

In [ ]:
df_products = TransformacionMinuscula(df_products, "product_category_name");
#Se pasan todos los registros de product_category_name a minusculas

Se visualiza para comprobar los cambios.

In [ ]:
df_products.info()
df_products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  string
 1   product_category_name       32341 non-null  string
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), string(2)
memory usage: 2.3 MB

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

Se observa la cantidad de nulos para realizar una accion que no afecte el resultado de analisis que se realice.

Cantidad de nulos:
* product_id:                    0
* product_category_name:         610
* product_name_lenght:           610
* product_description_lenght:    610
* product_photos_qty:   610
* product_weight_g:                2
* product_length_cm:               2
* product_height_cm:              2
* product_width_cm:              2

In [ ]:
#Se realiza un porcentaje de la cantidad de nulos
porcentaje_nulos = (df_products.isnull().sum() / len(df_products)) * 100

print(porcentaje_nulos)

product_id                    0.000000
product_category_name         1.851234
product_name_lenght           1.851234
product_description_lenght    1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_length_cm             0.006070
product_height_cm             0.006070
product_width_cm              0.006070
dtype: float64

Como la cantidad de nulos no es mayor al 10% se decide eliminar dichos registros.

In [ ]:
#Se guarda en una variable aquellas columnas que tengan menos del 10%

columnas_capturadas = porcentaje_nulos[porcentaje_nulos <= 10].index;

#Se borrara los datos de las columas que se capturaron en la variable columnas_capturadas

df_products.dropna(subset= columnas_capturadas, inplace =True);

#Se visualizara como queda la tabla con las modificaciones

df_products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

Por ultimo, se establece la columna √≠ndices de las tablas como la clave primaria en el DataFrame.

In [ ]:
#En este caso "product_id" seria la columna indice
df_products.set_index("product_id", inplace = True)

### Orders
Observamos los tipo de datos que tiene la tabla para aplicar las funciones realizadas anteriormente.

* order_id: object
* customer_id:                  object
* order_status:                object
* order_purchase_timestamp:       object
* order_approved_at:              object
* order_delivered_carrier_date:  object
* order_delivered_customer_date:  object  
* order_estimated_delivery_date:   object

A continuacion se modificara las columnas de tipo object a STRING:

In [ ]:
lista_string = ["customer_id", "order_id", "order_status"];
#Se realiza la transformacion de tipo de dato de las columnas que estan dentro de la lista
TransformarString(df_orders, lista_string);
#Se invoca a la funcion creada

Los datos de las siguientes columnas se pasaran a minuscula. Se modificara solo la columna product_category_name que sera necesaria para el analisis.

In [ ]:
df_orders = TransformacionMinuscula(df_orders, "order_status");
#Se pasan todos los registros de order_status a minusculas

Se transformaran las columnas tipo Object a Datetime:

In [ ]:
lista_date = ["order_purchase_timestamp",
              "order_approved_at",
              "order_delivered_carrier_date",
              "order_delivered_customer_date",
              "order_estimated_delivery_date"] #Se guardan las columnas en una lista

TransformarFecha(df_orders, lista_date) #Se visualizan los datos

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

Se visualizan los datos para corroborar que se hicieron correctamente los cambios

In [ ]:
df_orders.info()
df_orders.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  string
 1   customer_id                    99441 non-null  string
 2   order_status                   99441 non-null  string
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), string(3)
memory usage: 6.1 MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

Se observa la cantidad de nulos para realizar una accion que no afecte el resultado de analisis que se realice.

Cantidad de nulos:
* order_id:                        0
* customer_id:                         0
* order_status:                        0
* order_purchase_timestamp:            0
* order_approved_at:         160
* order_delivered_carrier_date:    1783
* order_delivered_customer_date:    2965
* order_estimated_delivery_date:      0

In [ ]:
#Se realiza un porcentaje de la cantidad de nulos
porcentaje_nulos_order = (df_orders.isnull().sum() / len(df_orders)) * 100

print(porcentaje_nulos_order)

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

Como la cantidad de nulos es menos al 10%, se decide eliminar los datos.

In [ ]:
#Se guarda en una variable aquellas columnas que tengan menos del 10%

columnas_capturadas_order = porcentaje_nulos_order[porcentaje_nulos_order <= 10].index;

#Se borrara los datos de las columas que se capturaron en la variable columnas_capturadas

df_orders.dropna(subset= columnas_capturadas_order, inplace =True);

#Se visualizara como queda la tabla con las modificaciones

df_orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

Por ultimo, se establece la columna √≠ndices de las tablas como la clave primaria en el DataFrame.

In [ ]:
#En este caso "order_id" seria la columna indice
df_orders.set_index("order_id", inplace = True)

### Order items
Observamos los tipo de datos que tiene la tabla para aplicar las funciones realizadas anteriormente.

*  order_id:        object
*  order_item_id:   int64  
*   product_id:    object
*   seller_id:     object
*   shipping_limit_date:  object
*   price:                float64
*   freight_value:       float64

A continuacion se modificara las columnas de tipo object a STRING:

In [ ]:
lista_string = ["product_id", "order_id", "seller_id"];
#Se realiza la transformacion de tipo de dato de las columnas que estan dentro de la lista
TransformarString(df_orders_items, lista_string);
#Se invoca a la funcion creada

Se transformaran las columnas tipo Object a Datetime:

In [ ]:
lista_date = ["shipping_limit_date"]; #Se guarda la columna a modificar dentro de una lista

TransformarFecha(df_orders_items, lista_date); #Se invoca a la funcion con los parametros dataframe y la variable anterior

Se visualizan los datos para corroborar que se hicieron correctamente los cambios

In [ ]:
df_orders_items.info()
df_orders_items.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  string
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  string
 3   seller_id            112650 non-null  string
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), string(3)
memory usage: 6.0 MB

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

Se observa la cantidad de nulos para realizar una accion que no afecte el resultado de analisis que se realicen.

* Cantidad de nulos:
* order_id:               0
* order_item_id:          0
* product_id:             0
* seller_id:              0
* shipping_limit_date:    0
* price:                  0
* freight_value:          0

No se aplicara ninguna funcion con tratamiento de nulos.

Por ultimo, se establece la columna √≠ndices de las tablas como la clave primaria en el DataFrame.

In [ ]:
#En este caso "order_item_id" seria la columna indice
df_orders_items.set_index("order_item_id", inplace = True)

### Order payments
Observamos los tipo de datos que tiene la tabla para aplicar las funciones realizadas anteriormente.

* order_id:             object
* payment_sequential:    int64  
* payment_type:          object
* payment_installments: int64  
* payment_value:  float64

A continuacion se modificara las columnas de tipo object a STRING:

In [ ]:
lista_string = ["order_id", "payment_type"];
#Se realiza la transformacion de tipo de dato de las columnas que estan dentro de la lista
TransformarString(df_orders_payment, lista_string);
#Se invoca a la funcion creada

Los datos de las siguientes columnas se pasaran a minuscula. Se modificara solo la columna product_category_name que sera necesaria para el analisis.

In [ ]:
df_orders_payment = TransformacionMinuscula(df_orders_payment, "payment_type");
#Se pasan todos los registros de customer_city a minusculas

Se visualizan los datos para corroborar que se hicieron correctamente los cambios

In [ ]:
df_orders_payment.info()
df_orders_payment.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  string
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  string
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), string(2)
memory usage: 4.0 MB

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

Se observa la cantidad de nulos para realizar una accion que no afecte el resultado de analisis que se realicen.

Cantidad de nulos:
* order_id:                0
* payment_sequential:      0
* payment_type:            0
* payment_installments:    0
* payment_value:           0

No se aplicara ninguna funcion con tratamiento de nulos.

##ANALISIS DE DATOS
Se realizaran diferentes analisis teniendo en cuenta la problematica descripta anteriormente, elaborando insighs que ayuden al progreso comercial de la empresa. Se comenzara con consultas generales que puedan ayudar a otras otras operaciones mas complejas.

In [ ]:
#Esta funcion va a brindar informacion general de cada columna
def analisisDF(df):
  print("------------------------------------------------")
  print("Variables cuantitativas: ")
  columnas_numericas= df.select_dtypes(include=['int', 'float']).columns; #El select_dtypes devuelve el tipo de columna que se haya especificado, en este caso las columnas de tipo int y float.
  if not columnas_numericas.empty :  #Realizamos un manejo de error con la condicion de que solo puedan ser descriptas las columnas que no esten vacias
    print(df[columnas_numericas].describe()); #Se muestra la descripcion de cada columna
    print("------------------------------------------------")
    print("Variables cualitativas")
  columnas_string = df.select_dtypes(include=['string']).columns; #En este caso el select_dtypes devuelve columnas de formato string
  if not columnas_string.empty:
    print(df[columnas_string].describe());

###Customer

Se conocera cuantos clientes han realizado un pedido dentro de la empresa. Conocer la cantidad de clientes que tiene esta empresa es esencial para entender su desempe√±o, orientar sus estrategias comerciales y mantenerse competitiva en el mercado.

In [ ]:
 #Usamos la funcion count() dentro de la tabla Ordenes para que obtenga la cantidad de clientes que hay dentro de la empresa.
clientes_unicos = df_orders["customer_id"].count();


print("El numero de cliente dentro del conjunto de datos es: ", clientes_unicos)

El numero de cliente dentro del conjunto de datos es:  96461

Observamos las variables cuantitativas y cualitativas:

In [ ]:
analisisDF(df_customer); #Realizamos un analisis general de la tabla por columna

------------------------------------------------
Variables cuantitativas:
       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000
------------------------------------------------
Variables cualitativas
                      customer_unique_id customer_city customer_state
count                              99441         99441          99441
unique                             96096          4119             27
top     8d50f5eadf50201ccdcedfb9e2ac8455     sao paulo             sp
freq                                  17         15540          41746

Se conocera cuantos clientes hay por ciudad, lo que ayudara a crear mas publicidad en lugares donde no haya tantas ventas. Identificar la ciudad donde mas se vende tambien contribuye al conocimiento del comprador.

In [ ]:
cantidadxciudad = df_customer["customer_city"].value_counts(); #Value_counts nos ayuda a contar los registros diferentes que hay dentro de customer_city
print(cantidadxciudad)

customer_city
sao paulo            15540
rio de janeiro        6882
belo horizonte        2773
brasilia              2131
curitiba              1521
                     ...
palmares paulista        1
pires ferreira           1
vicente dutra            1
alagoa nova              1
eugenio de castro        1
Name: count, Length: 4119, dtype: Int64

San Pablo es la ciudad donde viven la mayor parte de los clientes, puede ser porque es una de las ciudades mas grande de Brasil. Se podria pensar en mas sucursales en esa zona.

###Products

Se observara las variables cuantitativas y cualitativas:

In [ ]:
analisisDF(df_products);

------------------------------------------------
Variables cuantitativas:
       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32340.000000                32340.000000        32340.000000
mean             48.476592                  771.492393            2.188961
std              10.245699                  635.124831            1.736787
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32340.000000       32340.000000       32340.000000
mean        2276.956586          30.854545          16.958813
std         4279.291845          16.955965          13.636115
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32340.000000
mean          23.208596
std           12.078762
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000
------------------------------------------------
Variables cualitativas
       product_category_name
count                  32340
unique                    73
top          cama_mesa_banho
freq                    3029

Se determinara la categor√≠a de producto m√°s vendida para seguir apostando por la misma consiguiendo precios competitivos, gestionar mejor el inventario y agregar productos relacionados con esa categoria que den rentabilidad.

In [ ]:
df_merge_orderItem_product = pd.merge(df_orders_items, df_products, how= "inner", on = 'product_id'); #Se crea n merge que una la tabla productos con la de items
print(df_merge_orderItem_product["product_category_name"].value_counts()) #Cuenta la categoria de producto mas vendida

product_category_name
cama_mesa_banho                  11115
beleza_saude                      9670
esporte_lazer                     8641
moveis_decoracao                  8334
informatica_acessorios            7827
                                 ...
cds_dvds_musicais                   14
la_cuisine                          14
pc_gamer                             9
fashion_roupa_infanto_juvenil        8
seguros_e_servicos                   2
Name: count, Length: 73, dtype: Int64

Se observa que muebleria y articulos de belleza son las categorias mas vendidas. Se podria recomiendar la compra de productos de belleza que sean tendencias en redes sociales como: mascarillas, delineador, etc. En cuanto a seguros y servicios, que es la categoria que menos ha vendido, se podria optar por realizar promociones o no realizar pedido a proveedores.

###Orders

Observamos las variables cuantitativas y cualitativas:

In [ ]:
analisisDF(df_orders); #Aplicamos la funcion y como parametro usamos el df correspondiente

------------------------------------------------
Variables cuantitativas:
                             customer_id order_status
count                              96461        96461
unique                             96461            2
top     9ef432eb6251297304e76186b10a928d    delivered
freq                                   1        96455

Se calculara el n√∫mero total de pedidos que proporciona informaci√≥n valiosa para evaluar el rendimiento, planificar y evaluar el crecimiento empresarial.

In [ ]:
cantidad_pedidos = df_orders['order_status'].count(); #dentro de la variable contamos con count() cuantos registros de ordenes estan registrados.
print("cantidad de pedidos: ", cantidad_pedidos)

cantidad de pedidos:  96461

Se conocera la cantidad de dias que lleva la empresa dentro del mercado.

In [ ]:
tiempo_empresa = (df_orders["order_purchase_timestamp"].max()) - (df_orders["order_purchase_timestamp"].min()) #En la variable guardamos la diferencia de dias que hay entre la primera y la ultima order
print(tiempo_empresa)

713 days 02:43:59

En base al resultado anterior, se observara la cantidad de pedidos de acuerdo a los meses, y asi establecer algunas estrategias de mercado:

In [ ]:


print(df_orders['order_purchase_timestamp'].dt.month.value_counts())

order_purchase_timestamp
8     10544
5     10294
7     10028
3      9549
6      9231
4      9101
2      8197
1      7817
11     7288
12     5514
10     4748
9      4150
Name: count, dtype: int64

El mes que mas se vendio es Agosto y esto puede ser porque durante el invierno las personas no tienen gastos en salidas a diferencia del verano. En los meses donde no hay tantas ventas se puede plantear promociones u ofertas para mayor demanda. En diciembre deben lanzarse mas publicidad por la aproximacion a la fiestas.

###Order Items

Observamos las variables cuantitativas y cualitativas:

In [ ]:
analisisDF(df_orders_items)

------------------------------------------------
Variables cuantitativas:
               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000
------------------------------------------------
Variables cualitativas
                                order_id                        product_id  \
count                             112650                            112650
unique                             98666                             32951
top     8272b63d03f5f79c56e9e4120aec44ef  aca2eb7d00ea1a7b8ebd4e68314663af
freq                                  21                               527

                               seller_id
count                             112650
unique                              3095
top     6560211a19b47992c3666cc44a7e94c0
freq                                2033

Se conoce la cantidad de productos vendidos para identificar tendencias importantes en el mercado. Esto incluye cambios en la demanda del consumidor, preferencias de productos y comportamiento de compra, lo que permite a la empresa adaptarse y ajustar su oferta de productos en consecuencia.

In [ ]:
cantidad_prod_vendidos = df_orders_items["product_id"].count()
print(cantidad_prod_vendidos)

112650

###Order payment

In [ ]:
analisisDF(df_orders_payment)

------------------------------------------------
Variables cuantitativas:
       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000
------------------------------------------------
Variables cualitativas
                                order_id payment_type
count                             103886       103886
unique                             99440            5
top     fa65dad1b0e818e3ccc5cb0e39231352  credit_card
freq                                  29        76795

Se calcula el promedio de valor por pedido para entender como son las ventas y si tiene rentabilidad las estrategias de mercado.

In [ ]:
def payment_total(): #~Se crea una funcion para obtener el payment_total

  total= 0
  for columna in df_orders_payment:
    total = df_orders_payment["payment_value"] * df_orders_payment["payment_installments"]; #multiplica el pago con la cantidad de cuotas que el cliente solicito
  promedio = total.sum() / len(df_orders_payment); #Se suma todo el total y se lo divide por el tama√±o de orders payment
  return promedio;

print("El promedio de valor de pago por pedido es de : ", payment_total())

El promedio de valor de pago por pedido es de :  633.0319544500702

Se observa la cantidad de tipos de pagos utilizado por los clientes

In [ ]:
df_orders_payment["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: Int64

Se puede visualizar que tarjeta de credito es el medio de pago mas habitual, lo cual se concluye que las compras de mayor monto pueden ser solventada con cuotas, se podrian hacer promos de 3 cuotas sin interes o descuentos con debito para que este medio de pago sea mas viable.

##ELABORACION DE NUEVOS DATAFRAMES

In [ ]:
if not os.path.exists('dataset_tp'): #Se crea una carpeta par almacenar los dataframe en formato csv
  os.makedirs('dataset_tp')

### Orders - Order payment

In [ ]:
df_merge_order_payment = pd.merge(df_orders, df_orders_payment, how= "inner", on = 'order_id') #Se crea el dataframe por medio de un merge entre dos tablas
df_merge_order_payment.head()

In [ ]:
df_merge_order_payment.drop(['customer_id', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date'], axis= 1, inplace= True)
#Eliminamos aquellas columnas que no seran necesarias para el analisis

In [ ]:
df_merge_order_payment.head()

In [ ]:
df_merge_order_payment.to_csv('dataset_tp/order_payment.csv') #Guardamos en el df en formato csv

### Order items - Product

In [ ]:
#Creamos el dataframe con anterioridad, por ende solo lo vamos a visualizar
df_merge_orderItem_product.head()

In [ ]:
df_merge_orderItem_product.drop(['seller_id', 'product_id', 'shipping_limit_date', 'product_photos_qty', 'product_name_lenght', 'product_description_lenght'], axis= 1, inplace= True)
#Eliminamos aquellas columnas que no sean necesarias.

In [ ]:
df_merge_orderItem_product.head()

In [ ]:
df_merge_orderItem_product.to_csv('dataset_tp/orderItem_product.csv') #Se guarda en formato csv

### Order - Customer

In [ ]:
df_merge_order_customer = pd.merge(df_orders, df_customer, how= "inner", on = 'customer_id'); #Se crea el dataframe por medio de un merge entre dos tablas
df_merge_order_customer.head()

In [ ]:
df_merge_order_customer.drop([ 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix'], axis= 1, inplace= True)
#Eliminamos aquellas columnas que no seran necesarias para el analisis

In [ ]:
df_merge_order_customer.head()

In [ ]:
df_merge_order_customer.to_csv('dataset_tp/order_customer.csv') #Se guarda en formato csv

Se continuara el analisis en el archivo Excel, realizando tablas dinamicas y graficos que seran presentados en una dashboard.